[workspace]
resolver = "2"
members = ["cli", "node"]

[workspace.dependencies]
libp2p = { version = "0.52", features = ["full"] }
nmt-rs = "0.1.0"
node = { path = "node" }
tokio = { version = "1", features = ["full"] }
