[package]
name = "node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p.workspace = true
nmt-rs.workspace = true

dashmap = "5.5.3"
celestia-tendermint = "0.32.1"
hex = "0.4.3"
